### PR TITLE
species occ. v1 

### PR DESCRIPTION
**Pull request by sckott**

### CODE REVIEW

**Comment by sckott** [comment]
accidentially pulled upstream from master, so there's one of your older commits in there, just a .gitignore file change

**Comment by sckott** [comment]
I am still fixing some things in `spocc` and writing a new function for `spoccutils`, will update when those are done

**Comment by jhollist** [comment]
@sckott will the `spocc` and `spoccutils` updates impact the lesson as written?  Can I merge now or should I hold off?

**Comment by sckott** [comment]
I do have changes to make to the lesson - up to you - do you want me to update this before you merge? or i could add changes when ready

**Comment by jhollist** [comment]
I'll wait.  Got some other changes to deal with too.  Will merge tomorrow
PM.

**Comment by sckott** [comment]
@jhollist okay, all changes in, save a few small ones

**Comment by jhollist** [comment]
Great.  Once I get saag wiped off the baby, will merge!

On Thu, Jul 2, 2015 at 6:35 PM, Scott Chamberlain notifications@github.com
wrote:

> @jhollist https://github.com/jhollist okay, all changes in, save a few
> small ones
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jhollist/iale_open_science/pull/3#issuecomment-118185599
> .

## 

Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087

**Comment by jhollist** [comment]
Baby clean, feigning sleep and the additions look GREAT!

Thanks!

**Pull request merged**
